### ISSUE TITLE
Raw value for enum case is not unique

### ISSUE THREAD

**Issue by DominikPalo** [tingraldi/SwiftScripting#6]
Hi, I've used your tool to generate SB protocols for the Microsoft PowerPoint app, but project with these protocols cannot be build - it shows error `"Raw value for enum case is not unique"` The problem is that some generated enums contains same RAW values multiple times, for example `PowerPointEPPEntryEffect` contains `EntryEffectFade` and `EntryEffectFadeSmoothly` with same raw value `0xf60f09`

**Comment by tingraldi** [comment]
I've seen this same sort of error with other apps. The problem is in the scripting definition of the application itself. For PowerPoint, here's the relevant portion of the sdef that leads to this problem.

``` xml
<enumerator name="entry effect fade smoothly" code="0x00f60f09"/>
<enumerator name="entry effect fade" code="0x00f60f09"/>
```

A workaround is to edit the either the header file generated by `sdp` to remove or comment-out the duplicates (and then re-run `sbhc.py`) or edit the Swift file generated by `sbhc.py` to remove or comment-out the duplicates there.

In either case, you basically have to pick a winner amongst each set of conflicting values.
